name: ${CHATTER_ROLE:-talker}

services:
  chatter:
    build:
      dockerfile: Dockerfile.chatter
    depends_on: 
      husarnet: { condition: service_healthy } # husarnet service is healthy if all hosts listed in WAIT_HOSTNAMES are reachable
    network_mode: service:husarnet
    environment:
      - ROS_LOCALHOST_ONLY=1
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    command: ros2 run demo_nodes_cpp ${CHATTER_ROLE:-talker}

  bridge:
    build: .
    depends_on: 
      husarnet: { condition: service_healthy } # husarnet service is healthy if all hosts listed in WAIT_HOSTNAMES are reachable
    network_mode: service:husarnet
    volumes:
      - ./${CHATTER_ROLE:-talker}-config.json5:/config.json5
    environment:
      - ROS_DISTRO=jazzy
    command: zenoh-bridge-ros2dds -c /config.json5

  husarnet:
    image: husarnet/husarnet:2.0.180
    volumes:
      - /var/lib/husarnet
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - HOSTNAME=${CHATTER_ROLE:-talker}-host
      - JOINCODE
      - HUSARNET_DEBUG=1
      - WAIT_HOSTNAMES=talker-host,listener-host